yaff:
  ewald_alphascale: 3.5
  ewald_gcutscale: 1.1
  rcut: 10.0
  supercell: [4, 1, 3]
  switch_width: 0.0
  tailcorrections: false


conversion:
  kind: explicit

validations:
  - singlepoint:
      platforms: ['Reference']
      separate_parts: False
