name: Python Application

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      #      - uses: actions/checkout@v2
      #      - name: Set up Python 3.8
      #        uses: actions/setup-python@v2
      #        with:
      #          python-version: 3.8
      #
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v1
        with:
          token: fea4705c-9b79-49f7-92d6-2d12d25cac15
          verbose: True
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: testenv
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda activate testenv
          conda env update --name testenv --file environment.yml

          # install YAFF manually as conda package is outdated
          git clone https://github.com/molmod/yaff
          cd yaff
          python setup.py install
          cd ..
          rm -rf yaff

      - name: Install openyaff
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda activate testenv
          echo 'TESTMESSAGE'
          python setup.py install

      - name: Execute tests
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda activate testenv
          echo 'TESTMESSAGE'
          pip install pytest pytest-cov
          pytest --pyargs openyaff
